# Generated by Django 5.0.2 on 2024-05-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebooktopics',
            name='url',
        ),
        migrations.AlterField(
            model_name='guidebooktopics',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.guidebookorder'),
        ),
    ]
