# Generated by Django 5.0.2 on 2024-05-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_guidebooktopics_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarypage',
            name='information',
            field=models.TextField(default='Информация отсутсвует'),
        ),
        migrations.AlterField(
            model_name='dictionarypage',
            name='word',
            field=models.CharField(default='Без названия', max_length=255),
        ),
        migrations.AlterField(
            model_name='guidebookitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskdifficultаrchitecture',
            name='category',
            field=models.ManyToManyField(related_name='tasksDifficultArchitecture', to='index.taskcategory'),
        ),
        migrations.AlterField(
            model_name='tasksimple',
            name='category',
            field=models.ManyToManyField(related_name='tasks', to='index.taskcategory'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='category',
            field=models.ManyToManyField(related_name='theory', to='index.taskcategory'),
        ),
    ]
